// <auto-generated />
using CrowdedBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrowdedBackend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250331085534_RaspDataMigration")]
    partial class RaspDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrowdedBackend.Models.RaspData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("macAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("signalStrengthRSSI")
                        .HasColumnType("integer");

                    b.Property<int>("timestamp")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("RaspData");
                });
#pragma warning restore 612, 618
        }
    }
}
