// <auto-generated />
using System;
using CrowdedBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrowdedBackend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250415080424_CrowdedMigration")]
    partial class CrowdedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrowdedBackend.Models.DetectedDevice", b =>
                {
                    b.Property<int>("detectedDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("detectedDeviceId"));

                    b.Property<double>("deviceX")
                        .HasColumnType("double precision");

                    b.Property<double>("deviceY")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("venueID")
                        .HasColumnType("integer");

                    b.HasKey("detectedDeviceId");

                    b.HasIndex("venueID");

                    b.ToTable("DetectedDevice");
                });

            modelBuilder.Entity("CrowdedBackend.Models.RaspberryPi", b =>
                {
                    b.Property<int>("RaspberryPiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaspberryPiID"));

                    b.Property<int>("VenueID")
                        .HasColumnType("integer");

                    b.Property<double>("raspX")
                        .HasColumnType("double precision");

                    b.Property<double>("raspY")
                        .HasColumnType("double precision");

                    b.HasKey("RaspberryPiID");

                    b.HasIndex("VenueID");

                    b.ToTable("RaspberryPi");
                });

            modelBuilder.Entity("CrowdedBackend.Models.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenueID"));

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VenueID");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("CrowdedBackend.Models.DetectedDevice", b =>
                {
                    b.HasOne("CrowdedBackend.Models.Venue", "Venue")
                        .WithMany("DetectedDevices")
                        .HasForeignKey("venueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("CrowdedBackend.Models.RaspberryPi", b =>
                {
                    b.HasOne("CrowdedBackend.Models.Venue", "Venue")
                        .WithMany("RaspberryPis")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("CrowdedBackend.Models.Venue", b =>
                {
                    b.Navigation("DetectedDevices");

                    b.Navigation("RaspberryPis");
                });
#pragma warning restore 612, 618
        }
    }
}
