on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known-hosts
          echo "SSH keys installed successfully"

      - name: Debug SSH Key
        run: |
          echo "SSH Key Length:"
          wc -c < ~/.ssh/id_rsa
          echo "First few lines:"
          head -n 5 ~/.ssh/id_rsa
          echo "Last few lines:"
          tail -n 5 ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "echo 'SSH Connection Successful'"

      - name: Connect and pull
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
          cd "${{ secrets.WORK_CIR }}"
          git checkout "${{ secrets.MAIN_BRANCH }}"
          git pull
          EOF

      - name: Cleanup
        run: rm -rf ~/.ssh
