on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to private server and pull code
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ~/CrowdedRegionControl && git pull'
