on:
  push:
    branches:
      - main

jobs:
  test_ssh:
    runs-on: self-hosted
    steps:
      - name: Debug secrets
        run: |
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SSH_HOST: ${{ secrets.SSH_HOST }} test"
          echo "SSH_PASSWORD (first 100 chars): $(echo "${{ secrets.SSH_PASSWORD }}" | cut -c1-100)"

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass  # Install sshpass if not available

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.USER}}@${{ secrets.HOST }}
