on:
  push:
    branches:
      - main

jobs:
  test_ssh:
    runs-on: self-hosted
    steps:
      - name: Debug secrets
        run: |
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_PRIVATE_KEY (first 100 chars): ${{ secrets.SSH_PRIVATE_KEY | truncate 100 }}"
      - name: Check SSH tools
        run: |
          which ssh
          which ssh-keygen
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add SSH Host Key
        run: |
           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Run SSH command
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "Hllo from GitHub Actions!"'
